### ISSUE TITLE
Error in .NET Core 2.0 project when using <layout type="log4net.Layout.XmlLayoutSchemaLog4j" /> in log4net.Appender.UdpAppender

### ISSUE THREAD

**Issue by pmout** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#27]
When use <layout type="log4net.Layout.XmlLayoutSchemaLog4j" />  I got the error:

log4net:ERROR [UdpAppender] ErrorCode: WriteFailure. Unable to send logging event to remote host 127.0.0.1 on port 7071.
System.ArgumentException: Invalid name character in 'log4j:event'. The ':' character, hexadecimal value 0x3A, cannot be included in a name.
   at System.Xml.XmlWellFormedWriter.CheckNCName(String ncname)
   at System.Xml.XmlWellFormedWriter.WriteStartElement(String prefix, String localName, String ns)
   at log4net.Layout.XmlLayoutSchemaLog4j.FormatXml(XmlWriter writer, LoggingEvent loggingEvent)
   at log4net.Layout.XmlLayoutBase.Format(TextWriter writer, LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.RenderLoggingEvent(LoggingEvent loggingEvent)
   at log4net.Appender.UdpAppender.Append(LoggingEvent loggingEvent)

This problem is not directly related with this extension but as it depends of log4net.dll it is not possible to fix it.

**Comment by huorswords** [comment]
Hello @pmout ,

Thank you by your interest on this library.

As you say in your OP, this is not an issue of this library, instead of log4net package (https://github.com/apache/logging-log4net).

Looking at your exception, for me seems that you have configured your UdpAppender giving to it an invalid name. Why you don't just remove the ":" from the name of your appender?

Anyway, I don't see how can I help you if the issue is not directly related to the intention of this package, that is just to add the possibility to use log4net from the ASP .NET Core Logging System.

Maybe I'm missing something...

Regards

**Comment by huorswords** [comment]
Thank you by your answer @pmout .

Anyway, your issue still seems external to this library, looking at the exception stack that you provide on the OP.

Please, can you raise your issue on the log4net project repository?

Regard
