### ISSUE TITLE
Support for a log4net configuration outside of this package

### ISSUE THREAD

**Issue by kadukf** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#28]
We have a use-case that we configure log4net outside of the library. I'd like to add there a support for it.

so that I would be able to create new Log4NetProvider() w/o providing the cfg file name.

**Comment by huorswords** [comment]
Hello @kadukf ,

Thank you by open this issue.

* Do you mean that you expect that the `XmlConfigurator.Configure(loggerRepository, Parselog4NetConfigFile(log4NetConfigFile));` is directly not executed?
* Can you extend your use-case in order to figure out what is the exact scenario and what are you expecting for?

Thank you.

**Comment by huorswords** [comment]
Ok, I just saw your PR  #29

**Comment by af4jm** [comment]
This would be great for us, we have a config service.  Then we could pull a setting from there with the XML so we don't have the DB connection string in the git repo.  Much cleaner than trying to hack an override of Parselog4NetConfigFile.
