### ISSUE TITLE
Add or Change package name to Microsoft.Extensions.Logging.Log4Net ?

### ISSUE THREAD

**Issue by metavige** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#4]
I think this package that can use in DotNet console application.

Is that ok ?

**Comment by huorswords** [comment]
Hello @metavige ,

Thank you by your interest on this.

Yes, you are right, the nuget package can be used on a .NET Core Console application.

But... changing the name of the nuget package involves to create a different one, because at the moment you uploaded a nuget package with a given name, this name cannot be changed.

I will review the impact to discontinue the current package to be replaced by a new one named as you are suggesting.

Regards

**Comment by metavige** [comment]
OK, Thanks.

**Comment by huorswords** [comment]
Hello @metavige,

I have tried to upload a package with your name suggestion, but the package name has been reserved, probably by Microsoft team.

So, the name change cannot be performed.

Thank you by your suggestion.

Regards.
