### ISSUE TITLE
Match the Microsoft.Extensions.Logging LogLevels CRITICAL and TRACE to the corresponding log4net.Core Levels

### ISSUE THREAD

**Issue by moberacker** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#44]
Hi,

could you please extend your Microsoft.Extensions.Logging.Log4Net.AspNetCore provider supporting correct matching of the Microsoft.Extensions.Logging LogLevels CRITICAL and TRACE to the corresponding log4net.Core Levels log4net.Core.Level.Critical and log4net.Core.Level.Trace by the following changes:

in e.g. Log4NetExtensions.cs
```
        static public void Critical(this log4net.ILog log, object message, System.Exception exception)
        {
            log.Logger.Log(null, log4net.Core.Level.Critical, message, exception);
        }

        static public void Trace(this log4net.ILog log, object message, System.Exception exception)
        {
            log.Logger.Log(null, log4net.Core.Level.Trace, message, exception);
        }
```
and in Log4NetLogger.cs

```
 public void Log<TState>(
            LogLevel logLevel,
            EventId eventId,
            TState state,
            Exception exception,
            Func<TState, Exception, string> formatter)
        {
           ...
           ...
                switch (logLevel)
                {
                    case LogLevel.Critical:
                        this.log.Critical(message, exception);
                        break;
                    case LogLevel.Trace:
                        this.log.Trace(message, exception);
                        break;
                    case LogLevel.Debug:
                        this.log.Debug(message, exception);
                        break;
                    case LogLevel.Error:
                        this.log.Error(message, exception);
                        break;
                    case LogLevel.Information:
                        this.log.Info(message, exception);
                        break;
                    case LogLevel.Warning:
                        this.log.Warn(message, exception);
                        break;
                    default:
                        this.log.Warn($"Encountered unknown log level {logLevel}, writing out as Info.");
                        this.log.Info(message, exception);
                        break;
                }
            }
        }

```
?

Regards,

**Comment by huorswords** [comment]
Hello @moberacker ,

No problem to add the Trace() extension method.

But with the Critical / Fatal one, I have concerns, because right now the Critical LogLevel already is registering a Fatal message. I will take a deep look and I'll be back to you.

Thank you by your help. Regards.

**Comment by huorswords** [comment]
Hello again @moberacker ,

Do you have any justification to propose to change from Fatal to Critical?

For me are both the same, considering this SO answer: https://stackoverflow.com/a/5278006/982431

Let me know your thougts on this.

**Comment by moberacker** [comment]
Hello @huorswords ,

because I think it's more usefull to map Microsoft.Extensions.Logging.LogLevel Critical to the depending level of the underlying Logging Framework if it is available. Maybe you could add an appsettings property to support this mapping by configuration?

Regards,
Markus

**Comment by huorswords** [comment]
Hello @moberacker ,

I am working for some time on this issue, and I have implemented a way to be able to use Critical instead Fatal following your suggestion and using your extension methods. Thank you very much.

To be able to setup the log level for critical messages within Critical level instead of the fatal one (by default), you should initialize AddLog4Net using a Log4NetProviderOptions class.

The `OverrideCriticalLevelWith` property of this class allows you to indicate `"Critical"` to let the logger know that should use Critical level instead of the Fatal level when a Critical message is sent to be written by the logger. Any other value, is not considered and use Fatal as default.

You can configure the Log4NetProviderOptions class by two ways:
- Manually on your code.
- When you initialize the log4net logging module, import the appsettings.json section, adding something like the following into your appsettings.json

```xml
"Log4NetCore": {
	"OverrideCriticalLevelWith": "Critical",
}
```

Is it a valid approach for you?

Thank you.

**Comment by moberacker** [comment]
Hello @huorswords ,

yes it's ok but don't forget to also include OverrrideTraceLevelWith : "Trace" to Log4NetCore.

Regrards,
Markus

**Comment by huorswords** [comment]
Available on v.2.2.5
