### ISSUE TITLE
Results are different when executed using "dotnet vstest" vs "Test Explorer" from Visual studio

### ISSUE THREAD

**Issue by jaydeept** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#58]
I am using log4net package inside my .Net Core 2.2 project,
In one of my test case, I am trying to compare the error which has been returned from `log4net.Appender.MemoryAppender.GetEvents().Single().RenderedMessage()`. When I execute from **Test Explorer**, the error is something like: 

> Thrown System.Collections.Generic.KeyNotFoundException "testMessage"\r\n  at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFramesRecursive (source file unavailable)\r\n  at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFrames (source file unavailable)

While using **dotnet vstest** the error is something like:

> Thrown System.Collections.Generic.KeyNotFoundException "testMessage"\r\n  at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.GetStackFramesRecursive (source file unavailable)\r\n  at LoggingUnitTests.Log4NetLogTestsLoggingEnabled.mytestcasename (source file unavailable)

If you will notice, the test case name i.e. mytestcasename is being added in error message string when executing from dotnet vstest. This inconsistent behavior should have been fixed.

**Comment by huorswords** [comment]
Hello @jaydeept ,

Thank you by opening this issue.

Could you confirm if the behavior is the same without using the nuget package of this project? I mean, using directly the log4net library within the `MemoryAppender` (both are implemented on https://github.com/apache/logging-log4net).

As far as I understand your issue, seems more related to the way that VS and dotnet CLI are executing the tests and returning the Exception messages rather than the nuget it is not doing properly its work.

But, please, could you confirm if the problem is reproduced without this library?

Thank you.

**Comment by jaydeept** [comment]
Yo are right, this is the issue with dotnetcore, I have raised an issue there.
https://github.com/dotnet/corefx/issues/34290
