### ISSUE TITLE
Will this be released soon?

### ISSUE THREAD

**Issue by wjdavis5** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#61]
I got pretty excited when I saw the `ExternalConfigurationSetup `property added in. When will this be available?

https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/blob/172b3a57403dd689428305890718f565d38eda85/src/Microsoft.Extensions.Logging.Log4Net.AspNetCore/Log4NetProvider.cs#L96

Or maybe a cTor allowing us to pass in a `Hierarchy` ?

**Comment by huorswords** [comment]
Hello @wjdavis5 ,

I've not defined yet the release date for the next version, but if you are so excited with this feature, I will try to deploy it during this week. ;)

I'm interested on your second proposal. For my understanding, which scenario you want to cover with the second proposal?

Thank you!

**Comment by wjdavis5** [comment]
Sure the 2nd idea was just an alternative semantic to providing our own configurations. Have a property on the object feels a little hidden, whereas having a cTor that takes a Hierarchy would have made it clear I could have passed in my own custom config.

**Comment by huorswords** [comment]
At first, thank you by your explanation, @wjdavis5.

On previous versions, this extension had a lot of constructor overrides, implemented to cover almost every possible common configuration values combination.

But, after some versions, I found that the most unified developer experience (from my point of view - of course, I can be wrong) is to provide a proper configuration / options object in order to fill it within the desired values and use it as the almost unique way to use the extension.

So, if the current possibilities cover the scenario, I commit to be more detailed within the documentation available, trying to not let the available properties somehow hidden.

In this case, I'm sorry but this constructor override will not be include (at least, by the moment).

Thank you very much again by your suggestions. :)
