### ISSUE TITLE
Output path problem when using Windows Service

### ISSUE THREAD

**Issue by fengbozs** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#81]
When using Windows service to host asp.net core web API, the log file is output to C: \ windows \ system32. Is there any way to specify the output to the root directory of the executing program?

**Comment by Hiram-G** [comment]
I have the same problem. Is that a config issue or a bug?

Can't see what to do in order to fix it.

 ```
logging.AddLog4Net(Path.Combine(Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location), "log4net.config"));
                           logging.SetMinimumLevel(LogLevel.Trace);
```

**Comment by huorswords** [comment]
Hello @fengbozs & @Hiram-G ,

Very sorry to be so late to answer your questions, but I'm really busy on latest months at office.

Both of you are indicating that the  log file's output is c:\windows\system32. This is a [work as-is](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-3.1&tabs=visual-studio#current-directory-and-content-root) behaviour working with windows' services.

I think that, if you already did not found any workaround or solution, you could specify an absolute path in your log4net appender configuration in order to specify another folder to write your log files. Or maybe, you could use an [environment variable](https://stackoverflow.com/a/55539847) in order to let the log4net library replace it during initialization.

From my side, I don't see how I can help here. This nuget is connecting log4net library with Microsoft.Extensions.Logging subsystem, but I'm not dealing directly with the appender configuration (this belongs to log4net library itself).

Hope it helps. Let me know your thoughts on this.

**Comment by rcarvalhoxavier** [comment]
Hello !
Here one workaround. According this answer [https://stackoverflow.com/a/17740933/945014](https://stackoverflow.com/a/17740933/945014)
We could set this property (bellow) in the Main method and make a small change at the log4net.config

Program.cs
```
 public static void Main(string[] args)
        {
            log4net.GlobalContext.Properties["LogPath"] = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);   //log file path                     
            CreateHostBuilder(args).Build().Run();
        }

 public static IHostBuilder CreateHostBuilder(string[] args)
        {
            return Host.CreateDefaultBuilder(args).UseContentRoot(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location))
               .ConfigureAppConfiguration((hostingContext, config) =>
               {
                   config.AddJsonFile("appsettings.json", true, true); 
               })
                 .ConfigureLogging((hostingContext, logging) =>
                {
                    logging.ClearProviders();
                    logging.AddLog4Net(Path.Combine(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location), "log4net.config"), true);
                })
                .ConfigureServices(services =>
                {
                    services.AddHostedService<Worker>();
                }).UseWindowsService();
        }
```

log4net.config

```
<log4net>
  <appender name="RollingLogFileAppender" type="log4net.Appender.RollingFileAppender">    
    <file type="log4net.Util.PatternString" value="%property{LogPath}\\Log\\" />        
    <staticLogFileName value="false" />
    <appendToFile value="true" />
    <rollingStyle value="Composite" />
    <datePattern value="yyyy-MM-dd'.log'" />
    <lockingModel type="log4net.Appender.FileAppender+MinimalLock" />
    <param name="maximumFileSize" value="10MB" />
    <param name="maxSizeRollBackups" value="90" />
    <layout type="log4net.Layout.PatternLayout,log4net">
      <param name="ConversionPattern" value="%d [%t] %-5p %c [%x] %10username - %m%n" />
    </layout>
  </appender>
  <root>    
    <appender-ref ref="RollingLogFileAppender" />
  </root>
</log4net>
```

**Comment by fengbozs** [comment]
Solved my problem，thank you for your answer

**Comment by Hiram-G** [comment]
log4net is a great logging tool and worked very well over the years. So thank you for that!

Just FYI: The current issue gave me the idea to check if that works with nLog. nLog does not have this issue.

No need to pass the path of the current directory.

**Comment by huorswords** [comment]
Hi @Hiram-G ,

Yes, agree with you that maybe another logging libraries does not have the issue, but this project is only to connect the original log4net library with the Microsoft.Extensions.Logging system. :)

From my perspective and unfortunately, the only that I can do is try to address it when the problem belongs to this project, not the log4net library itself.
