### ISSUE TITLE
appsettings.json - does this package have a "provider alias" like the built-in Microsoft providers?

### ISSUE THREAD

**Issue by mg-cleartel** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#90]
Hi, 
I'm using this package (very useful!) on a .Net Core 3.1 Web API project. 
I was having trouble configuring Debug messages to show up, which I think I can make work now by looking at issue #72 .
My log4net.config level was set to "All", but my appsettings.json had a "Logging:LogLevel:Default" set to "Information".
I believe that if I change this to "Debug", I will be able to get debug messages, based on your investigation for #72 .
However, Microsoft documentation says that I can override the settings for a specific provider (like their built in Console, EventLog, etc, ) by adding a section, e.g., "Logging:Console:LogLevel:Default", without changing the overall settings. To do this the name of that section needs to be the provider "Alias" - as in "Console" in my example.
My question is, does this package have such an Alias? I tried using "Log4Net" but that doesn't seem to work.
Thanks so much!

**Comment by mg-cleartel** [comment]
Sorry  -I should have verified before I posted - additional information below:

> I believe that if I change this to "Debug", I will be able to get debug messages, based on your investigation for #72 .

This did not work. Specifically, the log4net has a "Debug" level specified, and the appsettings.json "Logging:LogLevel:Default" is also set to Debug, but my Debug messages do not show up in the RollingFileAppender I have configured.

**Comment by mg-cleartel** [comment]
Sorry - further research led me to the final comment on #76 by tgillitzer, which allowed me to resolve the issue where I could not get the Debug messages to show - specifically, I had to also set the Logging:LogLevel:Default (to Debug) in appsettings.Development.json. 

So at this point, only my original question remains - specifically, is there an alias for this package provider name that I can use to control Logging in the appsettings json files without affecting the default for all providers.

Thanks!

**Comment by huorswords** [comment]
Hello @mg-cleartel ,

My apologies for answering you now, but latest months I were too busy with my work.

Interesting proposal. The answer is no, right now it is not any alias for this provider.

I have been investigating it, and thinking about your good idea, but suddenly I realized that the current log4net behavior to filter the log level is to define it in the log4net.config file itself.

So, when you want to setup a different level of logging for a given / all log4net appenders, you should configure it from log4net.config. It is the original library behavior.

But, it is a good idea, at all. Thank you for your question.

**Comment by richmcd** [comment]
Ran across this today as well.

I think having an alias on Log4NetProvider would allow for easier, and more centralized, configuration of filters within the Microsoft.Extensions.Logging framework.

To be fair, you don't need an alias to configure the Log4NetProvider within appsettings.json separately from other providers, you just need the fully qualified type name (Microsoft.Extensions.Logging.Log4NetProvider), but it would be easier to be able to simply type Log4Net in the same way you would to configure a Console provider.  This allows Log4Net to leverage the category filters provided by the Logging framework so events from System* and Microsoft* could have different logging levels than Default.

The change only requires the addition of the ProviderAliasAttribute on the Log4NetProvider class.  Something like:

    [ProviderAlias("Log4Net")]
    public class Log4NetProvider : ILoggerProvider, IDisposable, ISupportExternalScope
    {
        ...
    }

Then the appsettings.json would look something like:

    "Logging": {
        "Log4Net": {
            "LogLevel": {
                "Default": "Debug",
                "System": "Information",
                "Microsoft": "Information"
            }
        }
    }

Instead of:

    "Logging": {
        "Microsoft.Extensions.Logging.Log4NetProvider": {
            "LogLevel": {
                "Default": "Debug",
                "System": "Information",
                "Microsoft": "Information"
            }
        }
    }
